openapi: 3.0.1
info:
  title: Setok API
  version: v1
paths:
  /Home:
    get:
      tags:
        - Home
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
    post:
      tags:
        - Home
      parameters:
        - name: message
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SetokResult'
            application/json:
              schema:
                $ref: '#/components/schemas/SetokResult'
            text/json:
              schema:
                $ref: '#/components/schemas/SetokResult'
components:
  schemas:
    Message:
      type: object
      properties:
        id:
          type: integer
          format: int32
        content:
          type: string
          nullable: true
      additionalProperties: false
    SetokResult:
      type: object
      properties:
        message:
          type: string
          nullable: true
        date:
          type: string
          nullable: true
      additionalProperties: false